### PR TITLE
Upgrade

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit eb7cb43 has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit eb7cb43 with merge 4ad9281...

**Comment by ghost** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/badboy/nobsign/builds/145368727)
Approved by: badboy
Pushing 4ad9281859ef2e8126c7b23131516a7a26f8f543 to master...

**Pull request merged**
