### PR TITLE
With osx

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit 6c472b4 has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit 6c472b4 with merge 69709c1...

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit a27e9fb has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit a27e9fb with merge 0cd98dc...

**Comment by badboy** [comment]
@not-a-robot force

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit e3263ed has been approved by `badboy`

**Comment by ghost** [comment]
:zap: Test exempted - [status](https://travis-ci.org/badboy/nobsign/builds/152600650)

**Pull request merged**
